cwt-envelope-signed-csr-eat = {  
  ; The EAT Profile for Envelope-Signed CSR OCP will register
  &(eat-profile : 265 ) => ~oid ; "1.3.6.1.4.1.42623.1" - note: `~` strips CBOR tag #6.111(oid) from `oid`

  ; Issuer claim is StringOrURI (tstr)
  &(iss : 1) => tstr

  ; Nonce claim is nonce-type = bstr .size (8..64)
  ? &(nonce : 10) => bstr
  
  ; Private Claims (they have to be < -65536 for rfc8392)
  
  ; CSR bytestring
  &(csr: -70001) => bstr

  ; Attribute List of OIDs
  &(attrib: -70002) => [+ $key-attributes-type]
}

$key-attributes-type = tagged-oid-type

signed-cwt = #6.18(COSE-Sign1-envelope-signed-csr)

COSE-Sign1-envelope-signed-csr = [
  protected: bstr .cbor protected-esc-header-map
  unprotected: unprotected-esc-header-map
  payload: bstr .cbor cwt-envelope-signed-csr-eat 
  signature: bstr
]

protected-esc-header-map {
  ; Well-defined header fields
  &(alg-id: 1) => int
  &(content-type: 3) => tstr / int
  &(issuer-key-id: 4) => bstr
  ; User-defined fields
  * cose-label => cose-value
}

unprotected-esc-header-map = {
  ? &(x5-chain: 33) => bstr / [ 2*certs: bstr ]
  * cose-label => cose-value
}

