spdm-key = spdm-key-map / tagged-spdm-key-map

tagged-spdm-key-map = #6.572(spdm-key-map) ; speculative because IANA registry is still pending

$key-attributes-type = tagged-oid-type

; TODO: OCP will assign few attributes types but the field is not restricted to those

spdm-key-dict = {
  &(id: 0) => uint
  &(attrib: 1) => [+ key-attributes-type]
}

spdm-key-map = {
  &(key: 0) =>  [+ spdm-key-map]
}

